In [2]:
#import dependencies
import pandas as pd

In [3]:
#Load data
nyc_bike = "202001-citibike-tripdata.csv"

bike_load = pd.read_csv(nyc_bike)

In [4]:
#Calculate Age
bike_year = bike_load['birth year']

age_list = []

for y in bike_year:
    biker_age = 2020 - y
    age_list.append(biker_age)

In [17]:
bike_load['gender'].replace([0,1,2],['Unknown','Male','Female'],inplace=True)

bike_load['age'] = age_list

bike_load

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender,age
0,789,2020-01-01 00:00:55.3900,2020-01-01 00:14:05.1470,504,1 Ave & E 16 St,40.732219,-73.981656,307,Canal St & Rutgers St,40.714275,-73.989900,30326,Subscriber,1992,Male,28
1,1541,2020-01-01 00:01:08.1020,2020-01-01 00:26:49.1780,3423,West Drive & Prospect Park West,40.661063,-73.979453,3300,Prospect Park West & 8 St,40.665147,-73.976376,17105,Customer,1969,Male,51
2,1464,2020-01-01 00:01:42.1400,2020-01-01 00:26:07.0110,3687,E 33 St & 1 Ave,40.743227,-73.974498,259,South St & Whitehall St,40.701221,-74.012342,40177,Subscriber,1963,Male,57
3,592,2020-01-01 00:01:45.5610,2020-01-01 00:11:38.1550,346,Bank St & Hudson St,40.736529,-74.006180,490,8 Ave & W 33 St,40.751551,-73.993934,27690,Subscriber,1980,Male,40
4,702,2020-01-01 00:01:45.7880,2020-01-01 00:13:28.2400,372,Franklin Ave & Myrtle Ave,40.694546,-73.958014,3637,Fulton St & Waverly Ave,40.683239,-73.965996,32583,Subscriber,1982,Male,38
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1240591,1587,2020-01-31 23:59:26.8820,2020-02-01 00:25:54.4890,3244,University Pl & E 8 St,40.731437,-73.994903,3092,Berry St & N 8 St,40.719009,-73.958525,40662,Subscriber,1990,Male,30
1240592,222,2020-01-31 23:59:32.6410,2020-02-01 00:03:15.4720,383,Greenwich Ave & Charles St,40.735238,-74.000271,383,Greenwich Ave & Charles St,40.735238,-74.000271,28722,Subscriber,1983,Male,37
1240593,163,2020-01-31 23:59:39.1780,2020-02-01 00:02:23.0400,150,E 2 St & Avenue C,40.720874,-73.980858,411,E 6 St & Avenue D,40.722281,-73.976687,32530,Subscriber,1958,Female,62
1240594,327,2020-01-31 23:59:49.2310,2020-02-01 00:05:16.3790,483,E 12 St & 3 Ave,40.732233,-73.988900,3718,E 11 St & Avenue B,40.727464,-73.979504,15314,Customer,1994,Male,26
1240595,484,2020-01-31 23:59:57.0360,2020-02-01 00:08:01.1820,327,Vesey Pl & River Terrace,40.715338,-74.016584,534,Water - Whitehall Plaza,40.702551,-74.012723,30947,Subscriber,1987,Male,33

In [16]:
groupby_user = bike_load.groupby('usertype')

groupby_user['usertype'].count()

usertype
Customer        94777
Subscriber    1145819
Name: usertype, dtype: int64

In [7]:
bike_load.max()

tripduration                                    1952746
starttime                      2020-01-31 23:59:57.0360
stoptime                       2020-02-04 08:42:03.2980
start station id                                   3918
start station name         Wythe Ave & Metropolitan Ave
start station latitude                          40.8183
start station longitude                        -73.8979
end station id                                     3918
end station name           Wythe Ave & Metropolitan Ave
end station latitude                            40.8183
end station longitude                          -73.8979
bikeid                                            42091
usertype                                     Subscriber
birth year                                         2004
gender                                          Unknown
age                                                 135
dtype: object

In [8]:
cleaned_data = bike_load
# cleaned_data.max()

In [9]:
cleaned_data.to_csv("cleaned_nyc_data.csv",index=False)